### ISSUE TITLE
Broken since blink/chromium merge

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/timeline-url#21]
Because the two repos merge the second API call fails.

**Comment by paulirish** [comment]
**if chrome version is < 47.0.2519.0 then we're [pre-merge](https://www.chromium.org/blink/blink-post-merge-faq).**


I think we'll only be able to sniff the chrome version out of `navigator.appVersion` so lets use that to branch behavior.

**Comment by arthurvr** [comment]
> I think we'll only be able to sniff the chrome version out of navigator.appVersion so lets use that to branch behavior.

Yeah, sure, the sniffing isn't difficult but the problem is that omahaproxy seems to have updated (or just broken), and checking old versions using the API we used before breaks now. ([example](https://omahaproxy.appspot.com/webkit.json?version=45.0.2454.101))

**Comment by arthurvr** [comment]
@paulirish Would also like some thoughts on [this](https://github.com/ChromeDevTools/timeline-url/pull/22#discussion_r41294798) :)

**Comment by paulirish** [comment]
true! i thought that API was only busted for new versions, but no its ALL versions. oh boy.

can you file a crbug for that?

**Comment by arthurvr** [comment]
@paulirish [Done.](https://code.google.com/p/chromium/issues/detail?can=2&q=omahaproxy&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&id=540535&thanks=540535&ts=1444196492) Can you get it to the right people?

**Comment by paulirish** [comment]
yah!
